[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "yads-common"
version = "0.1.0"
description = "Shared GUI and utility libraries for YADS"
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
dependencies = [
    "PySide6",
    "PySide6-Fluent-Widgets",
    "darkdetect"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["yads_common*"]
